### ISSUE TITLE
negative value in initial scale factor

### ISSUE THREAD

**Issue by YunxiaoT** [drewpendergrass/CHEEREIO#14]
Initialize_scaling_factors.py creates negative scale factors. The issue arises from the line 154 of the file, where the mean of the scale factor is transformed to be 1. Replacing subtraction with division ensures that the mean is 1 while keeping the scale factor positive.

```python
scaling_factor_cube[:,ind,:,:] /= (scaling_factor_mean) #transform to mean of 1
```

**Comment by drewpendergrass** [comment]
Nice fix, thanks! I made the change the dev branch and it will be present in the next release.
